print('Nasema jina lako liko moyoni, my chununi,')
print('Ila machoni sikuoni ,hivi huruma hauoni,')
print('Nasema jina lako liko moyoni ,my chununi')
print('Hata machoni sikuoni, hivi huruma hauoni')
print('                                        ')
print('Yani sasa sio usingiz,')
print('Nasahau namba za wana napiga yakwako')
print('Unanipa uchizi , umearibu medula oblangata')
print('Huja miss ndiz,mimi kweli nimemiss bwana tu yakwako')
